### ISSUE TITLE
Move code into content using `type: app`

### ISSUE THREAD

**Issue by lc-d** [tracking-exposed/youtube.tracking.exposed#1]
Accordingly to @privatemaker I move yttrex hard-coded pages from the theme layout to the website content, using `type: app` in the *frontmatter*. In this way we can avoid to touch the theme, actually there are three images that belong to this website that I've upload on the theme folder.

**Comment by vecna** [comment]
this is used in some files (last.md, related.md) and not in other. I'm migrating the template along the update of compare and related 

a variation of c3app appear too in impact.md!
