### ISSUE TITLE
add incremental counter in CSV file 

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/youtube.tracking.exposed#19]
each time the evidence ID change in the CSV, an numeric counter should increment by one, this might help some data analysts

**Comment by vecna** [comment]
reccomendedAuthor is a missing key too

**Comment by vecna** [comment]
@SalvatoreRomano1 tomorrow you'll test it!

**Comment by vecna** [comment]
Change of procedure! I'll update the server and you'll test it :) this issue is closed when the CSV format is documented

**Comment by vecna** [comment]
has been tested ?

**Comment by SalvatoreRomano1** [comment]
this is working good, never had problems
