### ISSUE TITLE
new feature "pseudonym"

### ISSUE THREAD

**Issue by SalvatoreRomano1** [tracking-exposed/youtube.tracking.exposed#20]
It would be nice to add in the csv file that each user can also download the feature "pseudonym" to be able to marge different csv of different users to produce a comparison.
(In the csv that you can download from the "compare" function the pseudonym is already present with the name "watcher" )

**Comment by vecna** [comment]
this should be fixed online, please test it

**Comment by SalvatoreRomano1** [comment]
It works for the general csv with all the videos of an users, but not in the "compare function"

**Comment by vecna** [comment]
I see, the CSV depending from an individual videoId has not the watcher. that's true, and I'm still undecided in doing it or if put an additional anonymization layer and make dedicate pseudonyms for each video

**Comment by SalvatoreRomano1** [comment]
I think that it would be better to use the same pseudonym also for the videoId, so we can conduct collective analysis easily.

**Comment by vecna** [comment]
I'm concerned on the privacy implication of this; probably, the safest solution, would be the _tagging_
