### ISSUE TITLE
Error in the interface

### ISSUE THREAD

**Issue by SalvatoreRomano1** [tracking-exposed/youtube.tracking.exposed#22]
Some videos are not correctly reported in the personal user interface: not all the related are shown clicking the "related" function (sometime just 1, sometimes 19..). Also in the "csv" function, always for the statistics related to a single video, there is an error because it says that "the video has no related".
YtTREX record correctly the related list, as we can see from the "compare" section of the specific video, or downloading the full csv of the watched videos from the personal page of the user.

**Comment by vecna** [comment]
thanks, I saw the issue and I might have fixed it. please test it
