### ISSUE TITLE
The " | " error

### ISSUE THREAD

**Issue by SalvatoreRomano1** [tracking-exposed/youtube.tracking.exposed#24]
Starting from the evidences recorded from the " Ленинград | Leningrad " channel, I found that the tool has a problem with the | symbol. In fact (after few tests) I found that we do not have problems with Cyrillic alphabet, but we have problem just with that specific symbol, whether it’s in the title of the video or in the name of the channel.
When we have that symbol we do not have the recommended videos list recorded correctly: no recommended is recorded in the server, and in the "CSV of your activities" we have the a list of related took from an other videos previously recorded (if | is in the channel name) or we do not have anything related to the video (if | is in the title of the video).

**Comment by vecna** [comment]
![image](https://user-images.githubusercontent.com/89555/76153551-aae64000-60cd-11ea-9bd8-c1d39ab5e61b.png)

solved!
