### ISSUE TITLE
fixing homepage with covid modded picture

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/youtube.tracking.exposed#36]
![image](https://user-images.githubusercontent.com/89555/77343392-e4f04c80-6d31-11ea-8045-a2c9347ff7b7.png)

**Comment by spaghettinucleari** [comment]
![Screenshot_2020-03-23 COVID-19 recommended content mapping](https://user-images.githubusercontent.com/47795057/77350863-69949800-6d3d-11ea-8bd5-f463fa32b1c3.png)

**Comment by vecna** [comment]
issue completed!

**Comment by vecna** [comment]
![image](https://user-images.githubusercontent.com/89555/77597569-91cbf480-6eff-11ea-8563-e3b894eaeb12.png)
