### ISSUE TITLE
Cyrillic problem 

### ISSUE THREAD

**Issue by SalvatoreRomano1** [tracking-exposed/youtube.tracking.exposed#39]
Watching few Cyrillic videos, some evidences are broken:
- https://www.youtube.com/watch?v=89VrhvBEzUY
- https://www.youtube.com/watch?v=d2II8CxDKWI
With those videos the evidence is recorded in the /personal page, but the "compare" and "csv" functions are not available.

similar to the issue #24 --> https://github.com/tracking-exposed/youtube.tracking.exposed/issues/24

**Comment by vecna** [comment]
I think this is fixed, in the next days please check it out
