### ISSUE TITLE
fix CSV from personal page

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/youtube.tracking.exposed#48]
reported by @SalvatoreRomano1 the videos in the personal page do not allow CSV of individual videos

**Comment by vecna** [comment]
well, shouldn't be closed automatically, before we should test this.

**Comment by SalvatoreRomano1** [comment]
Actually the "csv" button for compare function in  /personal/index.html  seems to be absent.
The same button on compare page seems broken.

**Comment by vecna** [comment]
CSV download from personal page: *bug confirmed*: it exists but doesn't work. 
![image](https://user-images.githubusercontent.com/89555/98382386-6e4b5980-204b-11eb-9082-343dad2a3b19.png)

**Comment by SalvatoreRomano1** [comment]
Everything seems working now!
BOth: csv for search and for compare functions
